baseURL = 'https://nilaykumar.github.io/'
languageCode = 'en-us'
title = 'odds & ends'

assetDir = 'static/'

refLinksErrorLevel = 'warning'
refLinksNotFoundURL = '/404.html'

[params]
  custom_css = ["css/stylesheet.css"]
  math_js = ["js/tex-chtml-full.js"]
  xy_js = ["js/xyjax/xypic.js"]
  xypic_path = 'js/xyjax'

[markup.goldmark.renderer]
  unsafe = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'modus-vivendi'
    #style = 'catppuccin-frappe'
    # tabWidth = 4

[taxonomies]
  tag = 'tags'
