baseURL = 'https://nilaykumar.github.io/'
languageCode = 'en-us'
title = 'Odds & Ends'

assetDir = 'static/'

[params]
  custom_css = ["css/stylesheet.css"]
  math_js = ["js/tex-chtml-full.js", "js/xyjax/xypic.js"]
  xypic_path = 'js/xyjax'

[markup.goldmark.renderer]
  unsafe = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'modus-operandi'
    # tabWidth = 4

[taxonomies]
  category = 'categories'
  tag = 'tags'

[permalinks]
  [permalinks.section]
    blog = '/blog/'
    garden = '/garden/'
  #[permalinks.taxonomy]
    #tags = '/garden/tags/:slug/'
    #categories = '/garden/categories/:slug/'
  #[permalinks.term]
    #tags = '/garden/tags/:slug/'
    #categories = '/garden/categories/:slug/'
