#+title: innovation
#+date: <2025-03-17 Mon>
#+hugo_base_dir: ../..
#+hugo_section: garden
#+hugo_tags: technology
#+hugo_custom_front_matter: :progress new

* what is innovation?
** political and economic change
Xiaowei Wang writes in /Blockchain Chicken Farm/
#+begin_quote
It's not clear what exactly innovation is, but whatever it is, there is
apparently a paucity of this golden resource everywhere except Silicon Valley...
The word "innovation" was derogatory in the age of monarchs, as it referred to
political and economic change that could bring down empires, threatening the
status of kings and elites.
#+ATTR_HTML: :class attribution
Wang, /Blockchain Chicken Farm/, page 123
#+end_quote
The origin of the word was a surprise to me. On the one hand, Silicon Valley's
usage of the term innovation is still consistent with this medieval definition,
as their brash move-fast-and-break-things approach has indeed heralded massive
political and economic changes (whether the rest of us wanted it or not). These
changes have in many ways been for the worse when it comes to the working class
(platformization, enshittification, gig economies, ...). On the other hand,
instead of bringing down the empire,
#+begin_quote
Contemporary innovation in the United States and China appears to strengthen
rather than threaten the political and economic order of the world... Our
modern-day monarchs, corporations and CEOs, are unthreatened by innovation. It
begs the question: If innovation is so disruptive, why would it be embraced by
people with so much to lose?
#+ATTR_HTML: :class attribution
Wang, /Blockchain Chicken Farm/, page 124
#+end_quote
They are pointing out precisely this class character of Silicon Valley's
so-called "disruptive innovations", which unravels the seeming paradox posed by
the question.

** innovation sublime
Sadowski, in /The Mechanic and the Luddite/, takes a different approach. He
approaches innovation-as-idea:
#+begin_quote
It is a value that people prioritize over most others. It is a goal people
strive to acheive. It is an end that justifies almost any means necessary...
Innovation is a fetish: an object of obsession. Innovation is a feeling: a sense
of the sublime.
#+ATTR_HTML: :class attribution
Wang, /The Mechanic and the Luddite/, page 50
#+end_quote
This is innovation as viewed through the rose-tinted, venture-capital backed
Silicon Valley metaverse goggles. Sadowski urges us to descend from the idea-l
and return to the material:
#+begin_quote
Innovation is not a timeless category that exists across all space-time but is
instead the product of its context. That context determines the creation and
application, purpose and value of things marked as innovations.
#+ATTR_HTML: :class attribution
Wang, /The Mechanic and the Luddite/, page 52
#+end_quote
In our present neoliberal capitalist context, innovations are LLM-powered search
engines that are [[https://www.cjr.org/tow_center/we-compared-eight-ai-search-engines-theyre-all-bad-at-citing-news.php][confidently wrong more than 60% of the time]] and short-term
rental platforms that destroy housing markets. Our societies' notion of
innovation is not worked out democratically, Sadowski notes, but instead
"defined by what fits into [a VC's] portfolio of investments. Progress becomes
defined by what aligns with their profit motive." (p54) Again, the class
character of innovation is clear.

** culturally constructed
Wang provides an example of the historical and contextual contingency of
innovation in arguing that the distinct cultural notions of innovation in China
prevented Western tech companies from taking off there:
#+begin_quote
Companies like eBay floundered in China, straining under the local advantage
that Taobao had in understanding the Chinese market. Key details were missed,
including the fact that eBay brokers secondhand goods, but in China, buying
secondhand goods, especially clothing, is frowned upon... The great innovators
of the United States found that innovation was culturally constructed.
#+ATTR_HTML: :class attribution
Wang, /Blockchain Chicken Farm/, page 126
#+end_quote
This is an interesting argument, although Wang doesn't provide too much more
evidence to support it directly. I don't doubt that culture is a significant
influence, however, and much of their book is implicitly supporting evidence for
the claim.
